spring.application.name=Idemy
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update


# Faylın maksimum ölçüsü (məsələn: 50MB)
spring.servlet.multipart.max-file-size=50MB
# Bir sorğuda göndərilən cəmi fayl ölçüsü
spring.servlet.multipart.max-request-size=50MB

# Faylların yadda saxlanacağı qovluğun yolu (local yol)
file.upload-dir=C:\\Users\\huawei\\OneDrive\\Documentos\\upload_videos/